set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'L9'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'file:///home/gmarik/path/to/plugin'
Plugin 'rstacruz/sparkup',{'rtp':'vim/'}
Plugin 'user/L9',{'name': 'newL9'}
Plugin 'Valloric/YouCompleteMe'
call vundle#end() 	
:set nu
:set wrap
:set hlsearch
:set autoindent
:set backup
:set ruler
:set showmode
:syntax on
:syntax enable
:set bg=dark
